language: node_js
node_js:
  - 0.10
deploy:
  provider: heroku
  api_key:
    secure: Abr/baqyx9EXAGo5XZNdXbgfoGSKfydhoIDAdtWon/SHJrVPQqddSweSzjPNNeq5O1bAFVzEMVwhIphiYxJnha/Gr2Wj0TMG/fTckxJYKIfZO+jhO11g8VJrm4+0HEUyQc9N/z7yEBFC8G2GNiNrE/1QjVpM2kGsF6BzQhjzwcA=
  app: feedforce-hubot
  on:
    repo: feedforce/hubot
